spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driver-class-name=org: org.h2.Driver
    initialization-mode: ALWAYS
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto=none: update


logging:
  level:
    org.springframework.web: DEBUG

log4j:
  logger:
    org:
      springframework:
        batch: debug
        jdbc: debug

management:
  metrics:
    web:
      server:
        auto-time-requests: true
  endpoints:
    web:
      exposure:
        include: "*"

batch:
  bond:
    chunk: 256

metrics:
  console:
    enabled: true
    step: 15s